<?php
 defined('ABSPATH') || exit;
 function bp_pages(){return ['home'=>['title'=>'Início','slug'=>'inicio'],'gamer'=>['title'=>'Computadores Gamer','slug'=>'computadores-gamer'],'corporativo'=>['title'=>'Computadores Corporativos','slug'=>'computadores-corporativos'],'workstation'=>['title'=>'Workstation','slug'=>'workstation'],'contato'=>['title'=>'Contato','slug'=>'contato'],'sobre'=>['title'=>'Sobre a BluePC','slug'=>'sobre'],'loja'=>['title'=>'Onde comprar','slug'=>'onde-comprar'],'fire'=>['title'=>'Linha Fire','slug'=>'linha-fire'],'ludic'=>['title'=>'Linha Ludic','slug'=>'linha-ludic'],'aura'=>['title'=>'Linha Aura','slug'=>'linha-aura'],'pulse'=>['title'=>'Linha Pulse','slug'=>'linha-pulse'],'frag'=>['title'=>'Linha Frag','slug'=>'linha-frag']];}
 function bp_faq(){return ['Qual computador é ideal para mim?'=>'Para jogos, conheça nossas linhas Gamer. Para trabalho, estudos e rotinas administrativas, escolha a linha Corporativa. Para modelagem 3D, edição de vídeo e engenharia, conheça nossas Workstations. Nossa equipe ajuda você a escolher a configuração adequada.','Com quais componentes a BluePC trabalha?'=>'Trabalhamos com processadores Intel e AMD Ryzen e placas de vídeo NVIDIA GeForce e AMD Radeon. Os componentes variam conforme o modelo: confira a configuração completa no anúncio ou com nossa equipe.','O computador já vem montado?'=>'Sim. As máquinas são montadas por especialistas, passam por testes de estabilidade e desempenho e são embaladas para o transporte. Confira no anúncio os acessórios e o sistema operacional incluídos.','Como comprar meu BluePC?'=>'Você pode consultar os modelos nos nossos canais de marketplace ou conversar com a equipe pelo WhatsApp. Preços, disponibilidade e condições são informados no canal de compra.'];}
 function bp_section_head($eyebrow,$title,$desc=''){echo '<div class="section-heading"><p class="eyebrow">'.esc_html($eyebrow).'</p><h2>'.esc_html($title).'</h2>'.($desc?'<p>'.esc_html($desc).'</p>':'').'</div>';}
 function bp_cta(){?><section class="help-band"><div class="wrap help-inner"><div><p class="eyebrow">Vamos encontrar seu próximo PC</p><h2>Seu uso. Sua configuração.</h2><p>Conte o que você precisa. A BluePC ajuda na escolha.</p></div><a class="button light" href="<?php echo esc_url(bp_whatsapp()); ?>" target="_blank" rel="noopener">Conversar com a BluePC</a></div></section><?php }
 function bp_recovered_data(){static $data=null;if($data===null)$data=json_decode(file_get_contents(get_template_directory().'/inc/line-data.json'),true);return $data;}
 function bp_markets($context=''){
  if(!$context)$context=bp_current_key();$data=bp_recovered_data();$names=['kabum'=>'KaBuM!','mercado'=>'mercado livre','amazon'=>'amazon','shopee'=>'Shopee','magalu'=>'Magalu'];
  $defaults=['kabum'=>'https://www.kabum.com.br/busca/pc-gamer-bluepc','mercado'=>'https://www.mercadolivre.com.br/loja/bluepc','amazon'=>'https://www.amazon.com.br/s?k=bluepc+ludic','shopee'=>'https://shopee.com.br/oficial/search?keyword=computadores&shop=950046979','magalu'=>'https://www.magazineluiza.com.br/busca/computadores/?filters=brand---2eletro'];
  $specific=array_key_exists($context,$data['markets']);$links=$specific?$data['markets'][$context]:$defaults;
      $store_urls=['amazon'=>'https://www.amazon.com.br/stores/BluePc/page/A2E483D4-171C-48DD-8130-06BC1173F5F0?lp_asin=B0G6GLVDYL&ref_=ast_bln','mercado'=>'https://www.mercadolivre.com.br/loja/bluepc','magalu'=>'https://www.magazineluiza.com.br/lojista/2eletroinfo/','shopee'=>'https://shopee.com.br/2eletroinfo'];
if($context==='corporativo')$links['amazon']=$store_urls['amazon'];
if(!$links){echo '<p>Fale com nossa equipe para encontrar os modelos desta linha nos canais de compra.</p><a class="button" href="'.esc_url(bp_whatsapp('Olá! Quero consultar os modelos da linha '.ucfirst($context).'.')).'" target="_blank" rel="noopener">Consultar modelos '.esc_html(ucfirst($context)).'</a>';return;}
  echo '<div class="market-grid">';foreach($links as $key=>$default){$url=$store_urls[$key]??($specific?$default:bp_setting($key,$default));if(!$url)continue;echo '<a href="'.esc_url($url).'" target="_blank" rel="noopener">'.bp_market_logo($key,$names[$key]).'<span>Ver computadores</span></a>';}echo '</div>';
 }

 function bp_lines(){echo '<div class="line-grid">';foreach(['fire','ludic','aura','pulse','frag'] as $i=>$line){echo '<a class="line-card" href="'.esc_url(bp_url($line)).'">';bp_image($line,'Identidade da linha '.ucfirst($line));echo '<div><span class="small">0'.($i+1).' / BLUEPC GAMER</span><h3>'.ucfirst($line).'</h3><span class="text-link">Conhecer a linha</span></div></a>';}echo '</div>';}

function bp_market_logo($key,$name){
 $regions=['kabum'=>[146,408,288,121],'amazon'=>[479,408,285,121],'mercado'=>[819,408,383,121],'shopee'=>[1237,408,300,121],'magalu'=>[1572,408,366,121]];
 if(!isset($regions[$key]))return '<strong>'.esc_html($name).'</strong>';
 return '<svg class="market-logo" viewBox="'.implode(' ',$regions[$key]).'" role="img" aria-label="'.esc_attr($name).'" focusable="false"><title>'.esc_html($name).'</title><image href="'.esc_url(get_template_directory_uri().'/assets/marketplace-logos.png').'" width="2000" height="1000" /></svg>';
}
