<?php
$data=[
'gamer'=>['eyebrow'=>'BLUEPC GAMER','title'=>'O SEU PRÓXIMO<br><em>NÍVEL COMEÇA AQUI.</em>','desc'=>'Entre no jogo com um computador preparado para a sua experiência. Conheça as cinco linhas Gamer BluePC.','image'=>'pc-hero','alt'=>'Computador Gamer BluePC RGB','button'=>'Explore as linhas','anchor'=>'linhas','section'=>'Potência que vira jogo.','body'=>'Do jogador casual ao competitivo, a BluePC reúne configurações para diferentes experiências. Escolha sua linha e converse com nossa equipe sobre os jogos, a resolução e o desempenho que você procura.','items'=>['Jogos e entretenimento','Streaming e criação','Configurações para seu setup']],
'corporativo'=>['eyebrow'=>'BLUEPC CORPORATIVO','title'=>'SUA ROTINA.<br><em>MAIS PRODUTIVA.</em>','desc'=>'Computadores para trabalhar, estudar e fazer mais. No escritório ou no home office.','image'=>'office','alt'=>'Profissional trabalhando no escritório','button'=>'Encontre sua configuração','anchor'=>'aplicacoes','section'=>'Tecnologia que trabalha com você.','body'=>'Para rotinas administrativas, financeiras e escolares, a linha Corporativa BluePC combina produtividade, qualidade e custo-benefício. Encontre a configuração adequada para documentos, navegação, aplicativos de trabalho e suas tarefas do dia a dia.','items'=>['Escritórios e empresas','Home office','Estudos e educação']],
'workstation'=>['eyebrow'=>'BLUEPC WORKSTATION','title'=>'GRANDES IDEIAS.<br><em>MAIS POSSIBILIDADES.</em>','desc'=>'Potência para criação, modelagem e renderização. Uma estação de trabalho à altura dos seus projetos.','image'=>'workstation','alt'=>'Estação de trabalho para criação audiovisual','button'=>'Planeje sua workstation','anchor'=>'aplicacoes','section'=>'Seu projeto pede mais. A gente entende.','body'=>'Edição de vídeo, modelagem 3D, animação e engenharia exigem uma configuração bem escolhida. As Workstations BluePC são pensadas para fluxos de trabalho complexos, com capacidade de processamento e estabilidade para longas jornadas.','items'=>['Edição de vídeo e animação','Modelagem 3D e renderização','Engenharia e arquitetura']]];
$d=$data[$key]; ?>
<?php if($key==='gamer'): ?>
<section class="gamer-category-banner" aria-label="BluePC Gamer"><h1 class="screen-reader-text">Computadores Gamer BluePC — potência para jogar e criar sem limites</h1><a href="#linhas" aria-label="Conheça as linhas de computadores Gamer"><?php bp_image('gamer-category-banner','BluePC Gamer: potência para jogar e criar sem limites. Jogos, edição de vídeos, design 3D e multitarefa.','gamer-banner-image',true); ?></a></section>
<?php elseif($key==='workstation'): ?>
<section class="gamer-category-banner" aria-label="BluePC Workstation"><h1 class="screen-reader-text">Workstations BluePC — desempenho para projetos grandes</h1><a href="#aplicacoes" aria-label="Conheça as aplicações das Workstations BluePC"><?php bp_image('workstation-category-banner','BluePC Workstation: desempenho para projetos grandes. Arquitetura e renderização 3D, edição de vídeos, programação e multitarefa.','gamer-banner-image',true); ?></a></section>
<?php elseif($key==='corporativo'): ?>
<section class="gamer-category-banner" aria-label="BluePC Office"><h1 class="screen-reader-text">Computadores Corporativos BluePC — desempenho para o dia a dia</h1><a href="#aplicacoes" aria-label="Conheça as aplicações dos computadores Office BluePC"><?php bp_image('office-category-banner','BluePC Office: desempenho para o dia a dia. Produtividade, Pacote Office, home office, estudos e multitarefa.','gamer-banner-image',true); ?></a></section>
<?php else: ?>
<section class="category-hero <?php echo esc_attr($key); ?>"><div class="wrap"><div><p class="breadcrumb"><?php bp_link('home','Início'); ?> / <?php echo esc_html(bp_pages()[$key]['title']); ?></p><p class="eyebrow"><?php echo esc_html($d['eyebrow']); ?></p><h1><?php echo wp_kses_post($d['title']); ?></h1><p><?php echo esc_html($d['desc']); ?></p><a class="button" href="#<?php echo esc_attr($d['anchor']); ?>"><?php echo esc_html($d['button']); ?></a></div><?php bp_image($d['image'],$d['alt'],'category-hero-image',true); ?></div></section>
<?php endif; ?>
<?php if($key==='gamer'):?><section class="section wrap" id="linhas"><?php bp_section_head('QUAL É A SUA LINHA?','Encontre a sua identidade Gamer.');bp_lines(); ?></section><?php endif; ?>
<section class="section wrap" id="aplicacoes"><div class="intro-columns"><div><p class="eyebrow">PENSADO PARA VOCÊ</p><h2><?php echo esc_html($d['section']); ?></h2></div><p><?php echo esc_html($d['body']); ?></p></div><div class="use-grid"><?php foreach($d['items'] as $i=>$item):?><article><span class="use-number">0<?php echo esc_html($i+1); ?></span><h3><?php echo esc_html($item); ?></h3><p><?php echo esc_html($key==='gamer'?'Encontre a configuração que combina com sua forma de jogar.':'Converse com nossa equipe para escolher os componentes de acordo com seus programas e necessidades.'); ?></p></article><?php endforeach; ?></div><div class="center"><a class="button outline" href="<?php echo esc_url(bp_whatsapp('Olá! Quero saber mais sobre a linha '.bp_pages()[$key]['title'].'.')); ?>" target="_blank" rel="noopener">Pedir orientação para escolher</a></div></section>
<section class="section market-section"><div class="wrap"><?php bp_section_head('ESCOLHA SEU CANAL','Seu BluePC está por aqui.','Consulte modelos, disponibilidade e condições nos nossos canais de compra.');bp_markets(); ?></div></section><?php bp_cta(); ?>
