<?php $banners=[['workstation','Workstation Gamer','Potência para jogar e desempenho profissional para projetos pesados.'],['gamer','PC Gamer Workstation','Para jogar, criar e realizar projetos de alta performance.'],['corporativo','PC Office','Praticidade e desempenho para trabalhar, estudar e navegar.']]; ?>
<section class="banner-slider" aria-roledescription="carrossel" aria-label="Destaques BluePC">
<h1 class="screen-reader-text">Computadores BluePC: Gamer, Workstation e Office</h1>
<div class="banner-slides">
<?php foreach($banners as $i=>$banner): ?>
<div class="banner-slide" role="group" aria-roledescription="slide" aria-label="<?php echo ($i+1).' de 3'; ?>" <?php if($i)echo 'aria-hidden="true" inert'; ?>>
<a class="banner-image" href="<?php echo esc_url(bp_url($banner[0])); ?>"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/banner-'.($i+1).'.webp'); ?>" width="<?php echo $i===2?2172:2244; ?>" height="<?php echo $i===2?724:701; ?>" alt="<?php echo esc_attr($banner[1].': '.$banner[2]); ?>" <?php echo $i===0?'fetchpriority="high"':'loading="lazy"'; ?> decoding="async"></a>
</div>
<?php endforeach; ?>
</div>
</section>
<div class="trust-strip"><div class="wrap"><span><b>01</b> Montagem especializada</span><span><b>02</b> Testado antes de chegar</span><span><b>03</b> Atendimento de verdade</span></div></div>
<section id="computadores" class="section wrap"><?php bp_section_head('ENCONTRE O SEU BLUEPC','Qual computador combina com você?','Conheça nossas três categorias e escolha de acordo com a sua rotina.'); ?><div class="category-grid computer-types">
<a class="category-card" href="<?php echo esc_url(bp_url('corporativo')); ?>"><div class="card-top"><span class="small">01 / DIA A DIA</span><span class="card-tag">OFFICE</span></div><?php bp_image('category-office-scene','Computador Office BluePC com monitor em ambiente de escritório','type-product'); ?><div class="card-body"><h3>Computador Office</h3><p>Praticidade para tarefas do dia a dia: Pacote Office, estudos, navegação na internet e rotinas administrativas.</p><span class="text-link">Conhecer PCs Office</span></div></a>
<a class="category-card" href="<?php echo esc_url(bp_url('workstation')); ?>"><div class="card-top"><span class="small">02 / PROJETOS EXIGENTES</span><span class="card-tag">WORKSTATION</span></div><?php bp_image('category-workstation-scene','Workstation BluePC com dois monitores exibindo projetos de arquitetura','type-product'); ?><div class="card-body"><h3>Computador Workstation</h3><p>Potência para programas exigentes de arquitetura, modelagem 3D e renderização, além de jogos pesados.</p><span class="text-link">Conhecer Workstations</span></div></a>
<a class="category-card" href="<?php echo esc_url(bp_url('gamer')); ?>"><div class="card-top"><span class="small">03 / JOGOS E EDIÇÃO</span><span class="card-tag">GAMER</span></div><?php bp_image('category-gamer-scene','Computador Gamer BluePC com iluminação RGB em setup para jogos e edição de vídeo','type-product'); ?><div class="card-body"><h3>Computador Gamer</h3><p>Desempenho para jogos pesados e programas de edição de vídeo e imagem. Para jogar e criar no mesmo setup.</p><span class="text-link">Conhecer PCs Gamer</span></div></a>
</div></section>

<section class="split-story wrap section"><div class="story-image"><?php bp_image('office','Profissional trabalhando em computador'); ?><span class="image-label">PARA O QUE MOVE VOCÊ</span></div><div><p class="eyebrow">CONHEÇA A BLUEPC</p><h2>Potência que impulsiona<br>o seu mundo.</h2><p>A BluePC é uma marca especializada na montagem de computadores Gamer e Office, desenvolvida para quem busca alto desempenho, confiabilidade e excelente custo-benefício.</p><p>Combinando componentes de qualidade, montagem especializada e um atendimento dedicado, entregamos máquinas prontas para atender desde as exigências dos jogos até as demandas do dia a dia no trabalho ou nos estudos.</p><p>Seja para jogar, criar ou produzir, a BluePC é a escolha certa para quem não abre mão de performance, durabilidade e preço justo.</p><?php bp_link('sobre','Conheça a BluePC','button outline'); ?></div></section>
<section class="section faq-section" id="duvidas"><div class="wrap faq-layout"><div><p class="eyebrow">SEM COMPLICAÇÃO</p><h2>Antes de escolher,<br>tire suas dúvidas.</h2><?php bp_link('contato','Fale com nossa equipe','text-link'); ?></div><div class="faq-list"><?php foreach(bp_faq() as $q=>$a):?><details><summary><?php echo esc_html($q); ?><span aria-hidden="true">+</span></summary><p><?php echo esc_html($a); ?></p></details><?php endforeach; ?></div></div></section>
<section class="section wrap reviews"><?php bp_section_head('QUEM JÁ ESCOLHEU BLUEPC','Experiências que fazem a diferença.'); ?><div class="review-grid"><blockquote><p>“Fui muito bem atendida desde o primeiro contato com a BluePC. Me explicaram tudo com paciência e me ajudaram a escolher o melhor setup.”</p><footer><strong>Jessica</strong><span>Administração</span></footer></blockquote><blockquote><p>“A máquina veio muito bem protegida, com ótima montagem e desempenho incrível.”</p><footer><strong>Alexandre</strong><span>Fotógrafo</span></footer></blockquote><blockquote><p>“A máquina chegou super bem embalada, com uma estrutura impecável e rodando perfeitamente.”</p><footer><strong>Marcelo</strong><span>Streamer</span></footer></blockquote><blockquote><p>“O atendimento foi excelente do início ao fim, e a entrega chegou até antes do prazo. Recomendo de olhos fechados!”</p><footer><strong>Heloisa</strong><span>Filmmaker</span></footer></blockquote></div></section>
<?php bp_cta(); ?>
